name: mimir
channels:
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - accelerate=0.21.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py310h2aa6e3c_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.5.0=h7ea286d_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hcb7b3dd_1
  - attrs=23.1.0=pyh71513ae_1
  - autogluon=0.8.2=light_hfa6e694_3
  - autogluon.common=0.8.2=pyhd8ed1ab_4
  - autogluon.core=0.8.2=light_py310h6c947df_6
  - autogluon.features=0.8.2=pyhd8ed1ab_3
  - autogluon.multimodal=0.8.2=pyha770c72_5
  - autogluon.tabular=0.8.2=pyha770c72_4
  - aws-c-auth=0.7.3=hab8b942_3
  - aws-c-cal=0.6.2=hb406d48_0
  - aws-c-common=0.9.0=hb547adb_0
  - aws-c-compression=0.2.17=he70778a_2
  - aws-c-event-stream=0.3.2=hcf14f3f_0
  - aws-c-http=0.7.12=he297698_1
  - aws-c-io=0.13.32=h3c776e5_2
  - aws-c-mqtt=0.9.5=h83b98fe_1
  - aws-c-s3=0.3.14=h24e141d_3
  - aws-c-sdkutils=0.1.12=he70778a_1
  - aws-checksums=0.1.17=he70778a_1
  - aws-crt-cpp=0.23.0=h04fc39a_5
  - aws-sdk-cpp=1.10.57=h0092a47_21
  - beautifulsoup4=4.12.2=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.4=hc338f07_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - boto3=1.28.39=pyhd8ed1ab_0
  - botocore=1.31.39=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_9
  - brotli-bin=1.0.9=h1a8c8d9_9
  - brotli-python=1.0.9=py310h0f1eb42_9
  - brotlipy=0.7.0=py310h8e9501a_1005
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.19.1=hb547adb_0
  - c-blosc2=2.10.2=h068da5f_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=hc5b65c1_1017
  - catalogue=2.0.9=py310hbe9552e_0
  - catboost=1.2.1=py310hbe9552e_0
  - cctools=973.0.1=hd1ac623_14
  - cctools_osx-arm64=973.0.1=h2a25c60_14
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2399d43_3
  - chardet=5.2.0=py310hbe9552e_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.7.3=py310hbe9552e_0
  - conda-build=3.26.1=py310hbe9552e_0
  - conda-index=0.2.3=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - confection=0.1.1=py310hc469350_0
  - cookiecutter=2.3.0=pyh1a96a4e_0
  - cryptography=41.0.3=py310hdd3b5e7_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cymem=2.0.7=py310h0f1eb42_1
  - cython-blis=0.7.10=py310ha11ecec_1
  - cytoolz=0.12.2=py310h2aa6e3c_0
  - dask-core=2023.8.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.14.4=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - evaluate=0.4.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - fastai=2.7.12=pyhd8ed1ab_0
  - fastcore=1.5.29=pyhd8ed1ab_0
  - fastdownload=0.0.7=pyhd8ed1ab_0
  - fastprogress=1.0.3=pyhd8ed1ab_0
  - filelock=3.12.3=pyhd8ed1ab_0
  - fmt=9.1.0=hffc8910_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py310h2aa6e3c_0
  - freetype=2.12.1=hd633e50_1
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.4.0=py310h2aa6e3c_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - gdk-pixbuf=2.42.10=h1ac0d0d_2
  - gdown=4.7.1=pyhd8ed1ab_0
  - gettext=0.21.1=h0186832_0
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.1=h1a8c8d9_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.33=pyhd8ed1ab_0
  - glob2=0.7=py_0
  - glog=0.6.0=h6da1cb0_0
  - gmp=6.2.1=h9f76cd9_0
  - gmpy2=2.1.2=py310h2e6cad2_1
  - google-auth=2.22.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h9f76cd9_1001
  - graphviz=8.1.0=h10878c0_0
  - grpcio=1.56.2=py310h95b248a_1
  - gtk2=2.24.33=h57013de_2
  - gts=0.7.6=he42f4ea_4
  - harfbuzz=8.1.1=hf1a6348_1
  - huggingface_hub=0.16.4=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.8.12=py310h342b742_0
  - imageio=2.31.1=pyh24c5eb1_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jxrlib=1.1=h27ca646_2
  - kiwisolver=1.4.5=py310h38f39d4_0
  - krb5=1.21.2=h92f50d5_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.15=hd835a16_1
  - ld64=609=h89fa09d_14
  - ld64_osx-arm64=609=hc4dc95b_14
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230125.3=cxx17_h13dd4ca_0
  - libaec=1.0.6=hb7217d7_1
  - libarchive=3.6.2=h82b9b87_1
  - libarrow=13.0.0=h6e4acf5_0_cpu
  - libavif=0.11.1=h9f83d30_2
  - libblas=3.9.0=17_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_9
  - libbrotlidec=1.0.9=h1a8c8d9_9
  - libbrotlienc=1.0.9=h1a8c8d9_9
  - libcblas=3.9.0=17_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.2.1=hc52a3a8_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.18=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.12=h2757513_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgd=2.3.3=h32cdd76_7
  - libgfortran=5.0.0=12_3_0_hd922786_1
  - libgfortran5=12.3.0=ha3a6a3e_1
  - libglib=2.76.4=h24e9cb9_0
  - libgoogle-cloud=2.12.0=h05652e3_1
  - libgrpc=1.56.2=h9075ed4_1
  - libiconv=1.17=he4db4b2_0
  - libjpeg-turbo=2.1.5.1=h1a8c8d9_0
  - liblapack=3.9.0=17_osxarm64_openblas
  - liblief=0.12.3=hb7217d7_0
  - libllvm15=15.0.7=h504e6bf_3
  - libmamba=1.5.0=h4fa9c85_0
  - libmambapy=1.5.0=py310hb7070d9_0
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.23=openmp_hc731615_0
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=4.23.3=hf32f9b9_0
  - librsvg=2.56.3=h0db3404_0
  - libsolv=0.7.24=ha614eb4_3
  - libsqlite=3.43.0=hb31c410_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.18.1=ha061701_2
  - libtiff=4.5.1=h23a1a89_1
  - libtool=2.4.7=hb7217d7_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libuv=1.46.0=hb547adb_0
  - libwebp=1.3.1=h3dd3bb6_0
  - libwebp-base=1.3.1=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxgboost=1.7.6=cpu_h7a1f521_2
  - libxml2=2.11.5=h25269f3_1
  - libzlib=1.2.13=h53f4e23_5
  - libzopfli=1.0.3=h9f76cd9_0
  - lightgbm=3.3.5=py310he38b2b1_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - llvm-openmp=16.0.6=h1c12783_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h642e427_1000
  - mamba=1.5.0=py310ha5d4528_0
  - markdown=3.4.4=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2aa6e3c_0
  - matplotlib-base=3.5.3=py310h78c5c2f_2
  - mdurl=0.1.0=pyhd8ed1ab_0
  - model-index=0.1.11=pyhd8ed1ab_0
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.0=he09a6ba_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.4=py310h8e9501a_0
  - multiprocess=0.70.15=py310h2aa6e3c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.9=py310h0f1eb42_1
  - ncurses=6.4=h7ea286d_0
  - networkx=3.1=pyhd8ed1ab_0
  - nlpaug=1.1.11=pyhd8ed1ab_1
  - nltk=3.8.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - nptyping=2.4.1=pyhd8ed1ab_0
  - numpy=1.25.2=py310haa1e00c_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - omegaconf=2.2.3=pyhd8ed1ab_0
  - openai=0.27.10=pyhd8ed1ab_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openmim=0.3.7=pyhd8ed1ab_0
  - openpyxl=3.1.2=py310h2aa6e3c_0
  - openssl=3.1.2=h53f4e23_0
  - orc=1.9.0=h858f345_1
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.1.0=py310h5924a0a_0
  - pandas-stubs=2.0.3.230814=pyhd8ed1ab_0
  - pango=1.50.14=hcf40dda_2
  - partd=1.4.0=pyhd8ed1ab_0
  - patch=2.7.6=h27ca646_1002
  - pathtools=0.1.2=py_1
  - pathy=0.10.2=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pillow=9.5.0=py310h60ecbdf_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - plotly=5.16.1=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - preshed=3.0.8=py310h0f1eb42_1
  - protobuf=4.23.3=py310hf4e154e_0
  - psutil=5.9.5=py310h8e9501a_0
  - pthread-stubs=0.4=h27ca646_1001
  - py-lief=0.12.3=py310h0f1eb42_0
  - py-xgboost=1.7.6=cpu_py310hccab3ec_2
  - pyarrow=13.0.0=py310h382c99a_0_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py310h8e9501a_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.12=py310h2aa6e3c_1
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h8e9501a_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytesseract=0.3.10=pyhd8ed1ab_0
  - python=3.10.12=h01493a6_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - python-graphviz=0.20.1=pyh22cad53_0
  - python-libarchive-c=5.0=py310hbe9552e_1
  - python-slugify=8.0.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-xxhash=3.3.0=py310h2aa6e3c_0
  - python_abi=3.10=3_cp310
  - pytorch=2.0.0=cpu_generic_py310h11b5426_1
  - pytorch-lightning=2.0.8=pyhd8ed1ab_0
  - pytorch-metric-learning=1.7.3=pyhd8ed1ab_0
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310hf1a086a_0
  - pyyaml=6.0.1=py310h2aa6e3c_0
  - re2=2023.03.02=hc5e2d97_0
  - readline=8.2=h92ec313_1
  - regex=2023.8.8=py310h2aa6e3c_0
  - reproc=14.2.4=h1a8c8d9_0
  - reproc-cpp=14.2.4=hb7217d7_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - rich=13.5.1=pyhd8ed1ab_0
  - ripgrep=13.0.0=h65448a5_2
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.17.32=py310h2aa6e3c_0
  - ruamel.yaml.clib=0.2.7=py310h8e9501a_1
  - s3transfer=0.6.2=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.3.3=py310had9acf8_0
  - scikit-image=0.19.3=py310h2b830bf_2
  - scikit-learn=1.3.0=py310h02d4e2a_0
  - scipy=1.11.2=py310h0975f3d_0
  - sentry-sdk=1.30.0=pyhd8ed1ab_0
  - seqeval=1.2.2=pyhd3deb0d_0
  - setproctitle=1.3.2=py310h8e9501a_1
  - setuptools=68.1.2=pyhd8ed1ab_0
  - shellingham=1.5.3=pyhd8ed1ab_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - smart_open=5.2.1=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h17c5cce_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spacy=3.6.1=py310h11c608e_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.4=pyhd8ed1ab_0
  - srsly=2.4.7=py310h1253130_0
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tapi=1100.0.11=he4954df_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310hfc83b78_0
  - text-unidecode=1.3=py_0
  - thinc=8.1.12=py310h11c608e_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2023.8.30=pyhd8ed1ab_0
  - timm=0.9.6=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tokenizers=0.13.3=py310he8402e3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchmetrics=1.0.3=pyhd8ed1ab_0
  - torchvision=0.15.2=cpu_py310he4f43cf_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - transformers=4.31.0=pyhd8ed1ab_0
  - typer=0.9.0=pyhd8ed1ab_0
  - types-pytz=2023.3.0.1=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typish=1.9.3=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py310h8e9501a_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wandb=0.15.9=pyhd8ed1ab_0
  - wasabi=1.1.2=py310hbe9552e_0
  - werkzeug=2.3.7=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xgboost=1.7.6=cpu_py310heb4de0d_2
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xxhash=0.8.2=hb547adb_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yaml-cpp=0.7.0=hb7217d7_2
  - yarl=1.9.2=py310h2aa6e3c_0
  - zfp=1.0.0=hb6e4faa_3
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstandard=0.19.0=py310h8e9501a_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - sentencepiece==0.1.96
prefix: /Users/philipp/miniforge3/envs/mimir
