name: mimir
channels:
  - conda-forge
dependencies:
  - autogluon=0.8.2
  - autogluon.common=0.8.2
  - autogluon.core=0.8.2
  - autogluon.features=0.8.2
  - autogluon.multimodal=0.8.2
  - autogluon.tabular=0.8.2
  - beautifulsoup4=4.12.2
  - boto3=1.28.39
  - conda=23.7.3
  - conda-build=3.26.1
  - conda-index=0.2.3
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - gmpy2=2.1.2
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - graphite2=1.3.13
  - graphviz=8.1.0
  - grpcio=1.56.2
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=8.1.1
  - huggingface_hub=0.16.4
  - icu=73.2
  - idna=3.4
  - imagecodecs=2023.8.12
  - imageio=2.31.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.3.2
  - jsonpatch=1.32
  - jsonpointer=2.0
  - jsonschema=4.17.3
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - langcodes=3.3.0
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libarchive=3.6.2
  - libarrow=13.0.0
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.76.4
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.2
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm15=15.0.7
  - libmamba=1.5.0
  - libmambapy=1.5.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=4.23.3
  - librsvg=2.56.3
  - libsolv=0.7.24
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libthrift=0.18.1
  - libtiff=4.5.1
  - libtool=2.4.7
  - libutf8proc=2.8.0
  - libuv=1.46.0
  - libwebp=1.3.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxgboost=1.7.6
  - libxml2=2.11.5
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightgbm=3.3.5
  - lightning-utilities=0.9.0
  - llvm-openmp=16.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.0
  - markdown=3.4.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.5.3
  - mdurl=0.1.0
  - model-index=0.1.11
  - more-itertools=10.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - munkres=1.1.4
  - murmurhash=1.0.9
  - ncurses=6.4
  - networkx=3.1
  - nlpaug=1.1.11
  - nltk=3.8.1
  - nomkl=1.0
  - nptyping=2.4.1
  - numpy=1.25.2
  - oauthlib=3.2.2
  - omegaconf=2.2.3
  - openai=0.27.10
  - openjpeg=2.5.0
  - openmim=0.3.7
  - openpyxl=3.1.2
  - openssl=3.1.2
  - orc=1.9.0
  - ordered-set=4.1.0
  - packaging=23.1
  - pandas=2.1.0
  - pandas-stubs=2.0.3.230814
  - pango=1.50.14
  - partd=1.4.0
  - patch=2.7.6
  - pathtools=0.1.2
  - pathy=0.10.2
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.2.1
  - pixman=0.40.0
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.16.1
  - pluggy=1.3.0
  - pooch=1.7.0
  - preshed=3.0.8
  - protobuf=4.23.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - py-lief=0.12.3
  - py-xgboost=1.7.6
  - pyarrow=13.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytesseract=0.3.10
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-graphviz=0.20.1
  - python-libarchive-c=5.0
  - python-slugify=8.0.1
  - python-tzdata=2023.3
  - python-xxhash=3.3.0
  - python_abi=3.10
  - pytorch=2.0.0
  - pytorch-lightning=2.0.8
  - pytorch-metric-learning=1.7.3
  - pytz=2023.3
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - re2=2023.03.02
  - readline=8.2
  - regex=2023.8.8
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - responses=0.18.0
  - rich=13.5.1
  - ripgrep=13.0.0
  - rsa=4.9
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - s3transfer=0.6.2
  - sacremoses=0.0.53
  - safetensors=0.3.3
  - scikit-image=0.19.3
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - sentry-sdk=1.30.0
  - seqeval=1.2.2
  - setproctitle=1.3.2
  - setuptools=68.1.2
  - shellingham=1.5.3
  - sigtool=0.1.3
  - six=1.16.0
  - sleef=3.5.1
  - smart_open=5.2.1
  - smmap=3.0.5
  - snappy=1.1.10
  - soupsieve=2.3.2.post1
  - spacy=3.6.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - srsly=2.4.7
  - sympy=1.12
  - tabulate=0.9.0
  - tapi=1100.0.11
  - tenacity=8.2.3
  - tensorboard=2.14.0
  - tensorboard-data-server=0.7.0
  - text-unidecode=1.3
  - thinc=8.1.12
  - threadpoolctl=3.2.0
  - tifffile=2023.8.30
  - timm=0.9.6
  - tk=8.6.12
  - tokenizers=0.13.3
  - tomli=2.0.1
  - toolz=0.12.0
  - torchmetrics=1.0.3
  - torchvision=0.15.2
  - tqdm=4.66.1
  - transformers=4.31.0
  - typer=0.9.0
  - types-pytz=2023.3.0.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typish=1.9.3
  - tzdata=2023c
  - unicodedata2=15.0.0
  - unidecode=1.3.6
  - urllib3=1.26.15
  - wandb=0.15.9
  - wasabi=1.1.2
  - werkzeug=2.3.7
  - wheel=0.41.2
  - xgboost=1.7.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.9.2
  - zfp=1.0.0
  - zipp=3.16.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - sentencepiece==0.1.96
prefix: /Users/philipp/miniforge3/envs/mimir
